### ISSUE TITLE
issue with hostname starting with 's'

### ISSUE THREAD

**Issue by roadrunnerjb** [BornToBeRoot/check_nextcloud#1]
HI,
thx for this nice plugin.

I use it for all of my nextcloud instances. 
With the last one I setup, I had some trouble with any check running with this script.

specifying --hostname=**scloud.my.domain** does not work wheras --hostname=**icloud.my.domain** works.

I always got HTTP 404

Digging into this I found that the statement:

`hostname = options.hostname.lstrip('[https|http]://').split('/')[0]`

manipulates my hostname to **cloud.my.domain**  (watch the missing 's') so that the resulting url gets invalid.

As I'm not familiar with python I made a workaround to just set

`hostname = options.hostname`

which works for me now

**Comment by kozliatko** [comment]
Yes, there is a problem with letters [https] and wrong usage of lstrip :)

A found this bug two days ago and solved this by regular expression. My solution you can find in pull requests.

**Comment by BornToBeRoot** [comment]
@kozliatko Thanks for the fix. I will take a look when i am back home.

**Comment by BornToBeRoot** [comment]
Thanks @roadrunnerjb @kozliatko 

PR #2 is merged.

You can download the new version.
