### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by waja** [BornToBeRoot/check_nextcloud#15]
Hi there,

as Python2 is not maintained [anymore](https://pythonclock.org/), is there a chance to get this plugin migrated over to Python3? [Fedora](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3) and [Debian](https://lists.debian.org/debian-python/2019/07/msg00080.html) dropping support for Python2 too.

Many thanks, Jan.

**Comment by BornToBeRoot** [comment]
PRs are welcome :)

I tried to migrate to Python 3 but i doesn't want to maintain both version.
Maybe now is the time. I would create a separate branch for 2.7 and the master would be on 3

Here is some code for Python 3
https://github.com/BornToBeRoot/check_nextcloud/commit/8ef9b437146d4524af147a28fa8d160fe0dedbc7

**Comment by waja** [comment]
> Here is some code for Python 3
8ef9b43

Is there a reason why you rolled this back code again?

**Comment by BornToBeRoot** [comment]
Sry for my late reply. There was no reason... i didn't want to maintain both versions.

I can migrate to Python3 when I have the need or some free time. PRs are also welcome.

**Comment by waja** [comment]
I'm not very familiar with python, but https://www.stxnext.com/blog/python-3-migration-guide/ seems to have a nice lazy point of start.
