### ISSUE TITLE
UNKOWN - [WEBREQUEST] 404 NOT found

### ISSUE THREAD

**Issue by Micka2302** [BornToBeRoot/check_nextcloud#16]
Hi,

I have problem with your script when I put this commands, the script give me back this error can you help me? 
 ./check_nextcloud.py -u mickael -p mickael -H 192.168.1.100/nextcloud -c system --protocol=http --ignore-proxy

**Comment by BornToBeRoot** [comment]
Hi,

Try to use --api-url=/nextcloud/ocs/...

And the hostname should only contain the ip or dns name.

**Comment by Micka2302** [comment]
Hi, 

Okay i solved my probleme, I have just created an virtualhost, and it's ok it's fix. 

(Sorry for my english i'm french) 

my commands ./check_nextcloud.py -u mickael -p mickael -H nextcloud.local -c system --protocol=http --ignore-proxy
and it's okay
