### ISSUE TITLE
Infalid Perfdata

### ISSUE THREAD

**Issue by MarcusCaepio** [BornToBeRoot/check_nextcloud#3]
Hi all,
according to the nagios plugin developement guide (https://nagios-plugins.org/doc/guidelines.html)
the performance data has to be in a strict format. The commas in the perfdata output from e.g. activeUsers are invalid, and so, monitoring solutions like Icinga2 ignoring them:

`[2018-11-29 15:59:27 +0100] warning/InfluxdbWriter: Ignoring invalid perfdata value: users_last_1_hour=20,
`
So I deleted the commas to get valid perfdata. PR is coming.

Cheers,
Marcus

**Comment by BornToBeRoot** [comment]
Thanks! I will take a look at this next week...
